#!/usr/bin/env python
import sys

phonetics = {
	'a' : 'alfa',
        'b' : 'bravo',
        'c' : 'charlie',
	'd' : 'delta',
	'e' : 'echo',
	'f' : 'foxtrot',
	'g' : 'golf',
	'h' : 'hotel',
	'i' : 'india',
	'j' : 'juliet',
	'k' : 'kilo',
	'l' : 'lima',
	'm' : 'mike',
	'n' : 'november',
	'o' : 'oscar',
	'p' : 'papa',
	'q' : 'quebec',
	'r' : 'romeo',
	's' : 'sierra',
	't' : 'tango',
	'u' : 'uniform',
	'v' : 'victor',
	'w' : 'whiskey',
	'x' : 'x-ray',
	'y' : 'yankee',
	'z' : 'zulu',
	'0' : 'zero',
	'1' : 'one',
	'2' : 'two',
	'3' : 'three',
	'4' : 'four',
	'5' : 'five',
	'6' : 'six',
	'7' : 'seven',
	'8' : 'eight',
	'9' : 'nine',
	'-' : 'dash',
	'@' : 'at',
	'.' : 'dot',
	',' : 'comma',
	'#' : 'number',
	'%' : 'percent',
	}

if len(sys.argv) == 1:
    print "no arguments"
else:
    phrase = sys.argv[1]
    words = [phonetics[c.lower()] for c in list(phrase)]
    print ' '.join(words)
